# Generated by Django 4.2.23 on 2025-08-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('customer_id', models.CharField(max_length=50, null=True, unique=True)),
                ('customer_email', models.EmailField(max_length=100, null=True)),
                ('customer_country', models.CharField(max_length=50, null=True)),
                ('customer_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
