# Generated by Django 4.2.23 on 2025-09-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0004_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
